spring:
  #   admin 监控平台
  #  boot:
  #    admin:
  #      client:
  #        url: http://127.0.0.1:6688

  # ${prefix}-${spring.profiles.active}.${file-extension}
  ## nacos 配置文件  consumer-dev.yml
  application:
    name: consumer
  profiles:
    active: dev


management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
logging:
  level:
    com:
      alibaba:
        cloud:
          client8081: debug



#feign:
#  sentinel:
#    enabled: true




